baseURL = "http://wwww.circlevilleonline.com/"
languageCode = "en-us"
title = "Circleville Online"
theme = "hoguej-mediumish"
copyright = "Circleville Online"
sectionPagesMenu = "main"
summaryLength = 25

[params.social]
  facebook = "CirclevilleOnline"